%% process group score
% compute averages and error bars classification accuracies over time
% written for data generated by "runGroup.m"
clear; clc; clf

listing = dir('groupScores/*.mat');
numFiles = size(listing,1);

for i = 1:numFiles
    fileName = listing(i).name;
    load(['groupScores/' fileName])
    
    % compute summarized data
    % mean 
    data.mean.acc(:,i) = mean(group.accuracy,2);
    data.mean.dev(:,i) = mean(group.deviation,2);
    data.mean.rep(:,i) = mean(group.response,2);
    % error bar 
    data.sd.acc(:,i) = std(group.accuracy');
    data.sd.dev(:,i) = std(group.deviation');
    data.sd.rep(:,i) = std(group.response');
end


%% Visualize the classification accuracy over time
% constant
d.FONTSIZE = 18;
d.LW = 2;
% Plot the CV accuracies against time
subplot(1,2,1)
plot(data.mean.acc,'linewidth',d.LW)
legend({'1%', '5%', '15%', '30%'}, 'location', 'southeast', 'fontsize', d.FONTSIZE-2)
xlabel('time', 'FontSize', d.FONTSIZE)
ylabel('performance (%)', 'FontSize', d.FONTSIZE)
title('Logistic regression accuracy against time', 'FontSize', d.FONTSIZE)

% Plot the sum of absolute deviations (on the test set) against time
subplot(1,2,2)
plot(1 - data.mean.dev,'linewidth',d.LW)
legend({'1%', '5%', '15%', '30%'}, 'location', 'southeast', 'fontsize', d.FONTSIZE-2)
xlabel('time', 'FontSize', d.FONTSIZE)
ylabel('$1 - \sum | \mathrm{deviation \hspace{2mm} from \hspace{2mm} targets}|  \hspace{.5cm} (target \in \{0,1\})$', 'FontSize', d.FONTSIZE,'Interpreter','latex')
title(' ''Fit ''against time', 'FontSize', d.FONTSIZE)

